version: "2"
services:
  lists-ms:
    build: .
    ports: 
      - "3003:3003"
    depends_on:
      - lists-db
  lists-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lists
      MYSQL_USER: listsuser
      MYSQL_PASSWORD: listsuser
    ports:
      - "27020:27020"
